# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b1746837a30a3d0ffaec89668210efc885c22dea53a6859ca8eb3398c00d4d161f8831797e49d6a11ddd870db25dddbbe749cd2b5093c5b39d4e97edd9755d

test:
  secret_key_base: 00a9f1573720fe28329068e80b03ab872fa1ef0722d60c57b000ef2f33b28cf9967f93c14acd862a6d9b799a43c9cba3910ba85ddd46229fdc4a45a7e02419fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
